all:
	g++ CG_HW2.cpp Camera.cpp Camera.h Mesh.cpp Mesh.h Renderer.cpp Renderer.h Shader.cpp Shader.h SkyBox.cpp SkyBox.h UAV.cpp UAV.h -o main -g -lglfw -lpthread -lX11 -ldl -lXrandr -lGLEW -lGL -DGL_SILENCE_DEPRECATION -DGLM_ENABLE_EXPERIMENTAL -I.
